paths:
  .github/workflows/**/*.{yml,yaml}:
    ignore:
      # actionlint's built-in runner label allowlist lags Blacksmith additions.
      # Keep runner validation enabled otherwise, but suppress this known false-positive.
      - 'label "blacksmith-16vcpu-[^"]+" is unknown\.'
